### ISSUE TITLE
Transfer to JouwWeb organization

### ISSUE THREAD

**Issue by roelvanduijnhoven** [JouwWeb/SlmQueueDoctrine#148]
We already decided to transferhttps://github.com/juriansluiman/SlmQueue to the JouwWeb organization. We also actively use SlmQueueDoctrine ourselves. I think it makes sense to also transfer this one to us. 

@basz and @juriansluiman Are you okay with this?

**Comment by basz** [comment]
no problem for me

**Comment by roelvanduijnhoven** [comment]
@juriansluiman Could you help us out by starting this transfer?

[The instructions are found here](https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/).

I sent you a invitation to join the JouwWeb team. This is necessary for the transfer to work. I will remove you once the transition is done.

Thanks for all your work on these packages, we'll try to keep them alive ;).

**Comment by juriansluiman** [comment]
👍 done

**Comment by imonteiro** [comment]
@juriansluiman @basz Do you use [SlmMail](https://github.com/juriansluiman/SlmMail)?

Just wondering if also make sense move it to JouwWeb organization, if @juriansluiman agrees.

**Comment by juriansluiman** [comment]
I am not active in the community anymore so I am willing to transfer to any
organisation which can support the continuity of Slm packages.

**Comment by roelvanduijnhoven** [comment]
Thanks @juriansluiman!

> Just wondering if also make sense move it to JouwWeb organization, if @juriansluiman agrees.

Yes, and we at JouwWeb also use it, so there's synergie there :). Let's move that one as well. 

I'll open a issue in SlmMail in a few seconds.

**Comment by roelvanduijnhoven** [comment]
@juriansluiman I went over your list of repo's, and opened an issue on every one that relates to either SlmQueue or SlmMail to transfer ownership. So: after these there should be no need to bother you again ;).

**Comment by juriansluiman** [comment]
I think all is done now
