### ISSUE TITLE
Zend-Expressive - how to run workers

### ISSUE THREAD

**Issue by chekubara** [JouwWeb/SlmQueueDoctrine#150]
Could someone explain how to run SlmQueueDoctrine worker with Zend Expressive?
Running `php public/index.php queue default --start` runs only main page of Zend Expressive application.

**Comment by roelvanduijnhoven** [comment]
I am not sure how expressive works differently from Zend Framework. On normal Zend `queue default --start` is a configured route in the console router.  

Once you find out how does works, I'd love to write about how you can do this in the repo: so feel free to create a PR at that point.

**Comment by basz** [comment]
There is no controller in an expressive application. I wrote a symfyny console command that I register on a bin/application.php that does the same thing.


```
<?php

declare(strict_types=1);

namespace HF\Api\Tools\Console\Command\Queue;

use SlmQueue\Controller\Exception\WorkerProcessException;
use SlmQueue\Exception\ExceptionInterface;
use SlmQueue\Queue\QueueInterface;
use SlmQueue\Queue\QueuePluginManager;
use SlmQueue\Worker\WorkerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputDefinition;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class ProcessCommand extends Command
{
    /**
     * @var WorkerInterface
     */
    protected $worker;

    /**
     * @var QueuePluginManager
     */
    protected $queuePluginManager;

    /**
     * @param WorkerInterface    $worker
     * @param QueuePluginManager $queuePluginManager
     */
    public function __construct(WorkerInterface $worker, QueuePluginManager $queuePluginManager)
    {
        $this->worker = $worker;
        $this->queuePluginManager = $queuePluginManager;

        parent::__construct();
    }

    /**
     * {@inheritdoc}
     */
    protected function configure(): void
    {
        $this
            ->setName('slm-queue:process')
            ->setDescription('Process the jobs')
            ->setDefinition(
                new InputDefinition([
                    new InputArgument('queueName', InputArgument::REQUIRED, 'Queue\'s name to process'),
                ])
            );
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $options = $input->getArguments();

        /** @var QueueInterface $queue */
        $queue = $this->queuePluginManager->get($options['queueName']);

        try {
            $messages = $this->worker->processQueue($queue, $options);
        } catch (ExceptionInterface $e) {
            throw new WorkerProcessException(
                'Caught exception while processing queue',
                $e->getCode(),
                $e
            );
        }

        $output->writeln($this->formatOutput($options['queueName'], $messages));

        return true;
    }

    /**
     * @param string $queueName
     * @param array  $messages
     *
     * @return string
     */
    protected function formatOutput($queueName, array $messages = [])
    {
        $messages = \implode("\n", \array_map(function ($m) {
            return \sprintf(' - %s', $m);
        }, $messages));

        return \sprintf(
            "Finished worker for queue '%s':\n%s\n",
            $queueName,
            $messages
        );
    }
}
‘’’

**Comment by chekubara** [comment]
What I understand is that you cannot configure console route in Zend Expressive. 
Most projects (for example Doctrine2) after installing put in folder  `vendor/bin/` scripts (bat and bash script) to run their console commands. But those scripts run php code from their vendor folder from `bin` folder.

**Comment by basz** [comment]
https://github.com/tommyseus/zend-expressive-symfony-console/

**Comment by imonteiro** [comment]
Quoting this [issue](https://github.com/zendframework/zend-expressive/issues/313):

> Expressive utilizes PSR-7 middleware, which is specifically for HTTP. As such, it cannot handle request/response pairs for console applications.
>
> To be honest, I was never comfortable with having zend-mvc handling console requests. The capabilities of http and console requests and responses are quite different, which means that you cannot realistically use the same action method to handle either type, at least not without a lot of branching. For this reason, we created zfcampus/zf-console; with it, you create dedicated console applications that you can have live within your existing application, but which do not use http facilities, and target side specifically console capabilities. You can reuse your service definitions easily, giving you access to the logic you write for your domain, but with a clean separation of concerns with regards to the environment.
>
> My own site does this; browse in the bin/ directory for the mwop.net command. I strongly recommend the approach.

@basz What about create a console command like [this ](https://github.com/weierophinney/mwop.net/blob/master/bin/mwop.net.php) approach?

**Comment by basz** [comment]
I never use expressive actions or zend-mvc for cli.  I eventually wrote my own SlmQueue commands and expose them via a bin/application.php. Like mwop is doing. I can donate these commands

**Comment by koenkivits** [comment]
The latest version integrates with `laminas-cli` -- the new CLI should also work with Mezzio out of the box. :)
