### ISSUE TITLE
Fatal error - DoctrineQueue is not compatibile with Interface

### ISSUE THREAD

**Issue by dcwq** [JouwWeb/SlmQueueDoctrine#159]
When i try to running default configuration on PHP 7.1 with this config:

'queue_manager' => [
  'factories' => [
    'default' => \SlmQueueDoctrine\Factory\DoctrineQueueFactory::class,
    ]
]

I got fatal error:

`Fatal error: Declaration of SlmQueueDoctrine\Queue\DoctrineQueue::recover($executionTime): int must be compatible with SlmQueueDoctrine\Queue\DoctrineQueueInterface::recover(int $executionTime): int in /var/www/web/vendor/slm/queue-doctrine/src/Queue/DoctrineQueue.php on line 20`

**Comment by roelvanduijnhoven** [comment]
@dcwq Mm that is a bug!

In https://github.com/JouwWeb/SlmQueueDoctrine/blob/master/src/Queue/DoctrineQueue.php#L284 it should say:

> public function recover(int $executionTime): int

Will fix that and cut a new version tuesday!

**Comment by roelvanduijnhoven** [comment]
@dcwq There is a new release that fixes this!
