### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by roelvanduijnhoven** [JouwWeb/SlmQueueDoctrine#168]
This issue is holding us back currently: https://github.com/doctrine/DoctrineModule/pull/727

**Comment by roelvanduijnhoven** [comment]
@basz A problem is that Laminas Console is deprecated. As the latest version does not support PHP 8, we need to replace the existing console controller. 

I implemented laminas-cli now. That library uses Symfony under the hood. 

I kept finding it difficult to test both for Laminas and Mezzio. For that reason I overhauled this repo, so it actually _tests_ both libraries. To make that worked I had to move the library source files into the `lib` directory. Maybe there is a better way; but I found this to be most easy to work with.

I also switched to GitHub workflows.

I know stuff is still in master; but feel free to comment. We can easily undo those changes!

Have a nice weekend :).

**Comment by basz** [comment]
Ok. Seems fine to me. One question. Dis packaging able to recognize this as now as a valid package? Since there is no composer.json in the root directory anymore?

Thanks for working on this!

**Comment by basz** [comment]
> Ok. Seems fine to me. One question. Dis packaging able to recognize this as now as a valid package? Since there is no composer.json in the root directory anymore?
> 
> Thanks for working on this!

Sorry. I ment; is packagist.org able to...

**Comment by roelvanduijnhoven** [comment]
Thanks for the quick feedback @basz! Bummer, you are true: this does not work. To remedy I moved around stuff a little bit, so the composer.json file is now still present in the root. I think this makes for a better solution in the end!

The CI will now still test both Mezzio and Laminas. I hope this will ease development :). But we'll see!

**Comment by basz** [comment]
There exists a plug-in for composer with which you are able to override a composer.json with a different one. That is useful for testing scenarios like this one. Maybe that can help. Something with "merge" in the name. (Sorry on mobile currently)

**Comment by roelvanduijnhoven** [comment]
I'll keep it as it is now, as it works ;). But happy to learn about new ways I could have done this easier. Do you mean https://github.com/wikimedia/composer-merge-plugin? Thanks @basz :pray:!

**Comment by basz** [comment]
Yes, that's the one. Used it once myself in https://github.com/bushbaby/BsbFlysystem to be able to test php7 and 8 which requires some differences in the composer... But if it works, it works.

**Comment by roelvanduijnhoven** [comment]
Damn. Actually pretty hard to navigate all those dependencies. Too many issues that I encounter when I try to tackle this upgrade. I'll postpone for some later time.
