### ISSUE TITLE
Implement --stop parameter to stop queue gracefully without console interaction

### ISSUE THREAD

**Issue by develart-projects** [JouwWeb/SlmQueueDoctrine#169]
We are using own script to (re)start queues, which is simply started by cron each minute and checking .lock files. When starting queue is needed, script start it. Works great.

However after new code deployment, we need to stop queues from within very same script. But we haven't such option, as --stop option is missing.

Is there any possibility to add --stop param to stop specific queue? Thank you in advance.

PS: meanwhile we are inspecting possibilities to extend controller and somehow add stop param temporarily.

**Comment by roelvanduijnhoven** [comment]
What do you mean with a stop command? If you invoke the console task, it will keep running in the foreground. So the way to _stop_ it, is just to KILL that script. That will close nicely, and you can restart the console task afterwards.

**Comment by develart-projects** [comment]
That works of course, but only when starting in the foreground. We are staring workers on the background, therefore I can't simply kill them. My question is, if there is any possibility to stop worker running in the background, let's say like daemon. Thank you.

**Comment by roelvanduijnhoven** [comment]
@develart-projects You are using your own script / thingy to start things in the background. So you will need a custom solution for your use-case. That is not something that we can implement in this repo. I'll close this issue.

Feel free to re-open if you misunderstood.

**Comment by basz** [comment]
You could write a strategy that detects file changes and halts the worker
